server.port=8082
spring.application.name=ms-andesstay-reservations

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#SIEMPRE cambiar ruta a la ruta de wallet descomprimida DE DEV, la ruta es el texto que va despues de ADMIN=
spring.datasource.url=jdbc:oracle:thin:@grupo11descloudnative_high?TNS_ADMIN=C:/Users/pinto/Desktop/Wallet_Grupo11DesCloudNative
spring.datasource.username=ADMIN
spring.datasource.password=FathiaBenjamin11
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
debug=true