server.port=8080
spring.application.name=ms-andesstay-bff

# CONFIGURACIÓN DE SEGURIDAD (RESOURCE SERVER - JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/15dd23f3-92e9-4574-8b7c-2cf6104370cd/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://9a8c1f22-da48-441c-8ba8-7f0fe7fadf57
# (Opcional) URL para obtener las llaves públicas y verificar la firma (JWKS)
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/<TU_TENANT_ID>/discovery/v2.0/keys


# ENRUTAMIENTO HACIA LOS MICROSERVICIOS (SPRING CLOUD GATEWAY)
# RUTA PARA EL CATALOGO
spring.cloud.gateway.routes[0].id=catalog-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/catalog/**
# RUTA PARA LAS RESERVAS
spring.cloud.gateway.routes[1].id=reservations-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/reservations/**

debug=true